site_name: My Awesome Project Docs
theme: material
nav:
    - Home: index.md
    - Page One: page1.md
    - Page Two: page2.md

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_generator: !!python/name:materialx.emoji.to_svg
          emoji_index: !!python/name:materialx.emoji.twemoji
    - pymdownx.tabbed
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.magiclink:
          repo_url_shorthand: true
          user: squidfunk
          repo: mkdocs-material
    - mermaid