
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DB_PATH=/app/data/figures.db
      - WATCH_FOLDER=/app/data/watch
      - LOG_FILE=/app/logs/ingestion.log
      - PYTHONPATH=/app
    restart: unless-stopped
